Update from OCA/master (#182)
* [FIX] missing-return: Incorrect check for tearDownClass (#362)

* [FIX] Pinned lazy-object-proxy for Python 2.7 (#365)

lazy-object-proxy is a library which astroids depends on. Astroid
is one of pylint's dependencies. Version 1.7.0 of lazy-object-proxy
fails to install on Python 2.7, therefore it was pinned to 1.6.0.

* [IMP] sql-injection: Detect possible sql injections when using f-strings (#364)

* [FIX] CI: Fix pluggy error on py3.7 and running lint only in one build (#366)

Travis has pre-installed a version of pluggy reproducing the following error when you try to install any pip package:

    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [22 lines of output]
        Traceback (most recent call last):
            File "<string>", line 36, in <module>
            File "<pip-setuptools-caller>", line 14, in <module>
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
            from setuptools.dist import Distribution
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
            from ._importlib import metadata
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
            disable_importlib_metadata_finder(metadata)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
            import importlib_metadata
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
            __version__ = version(__name__)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
            return distribution(package).version
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution
            return Distribution.from_name(package)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name
            dists = resolver(name)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
            found = self._search_paths(context.name, context.path)
        AttributeError: 'str' object has no attribute 'name'

It is related to the following thread:
 - https://stackoverflow.com/a/59549323/3753497

It was already fixed running the following command:
 - `pip install -U --force-reinstall pluggy`

Another change in the CI was running lints only for one build instead of all them

* [REF] requirements: Bump pylint package from 2.11.1 to 2.13.5 for py3.x (#367)

Changelog

Run the following command in pylint repo:
 - `git diff v2.11.1..v2.13.5`

* [ADD] pre-commit-hooks: Add pylint_odoo hook to be used from pre-commit.yaml directly (#368)

It will allow to add in your pre-commit.yaml directly an entry for pylint_odoo instead of pylint

  .pre-commit-config.yaml

    - repo: https://github.com/OCA/pylint-odoo
      rev: 5.0.5
      hooks:
        - id: pylint_odoo

You can get the current `rev` in the current tags:
 - https://github.com/OCA/pylint-odoo/tags

* [REF] README: Use new travis URL (#369)

Co-authored-by: Raf Ven <raf.ven@dynapps.be>
Co-authored-by: [Vauxoo] Antonio <101678296+antonag32@users.noreply.github.com>